# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{grope}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["youpy"]
  s.date = %q{2010-03-11}
  s.description = %q{A non-GUI library to represent browser environment using WebKit Framework}
  s.email = %q{youpy@buycheapviagraonlinenow.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "examples/js_minifier.rb",
     "examples/patterns.rb",
     "grope.gemspec",
     "lib/grope.rb",
     "lib/grope/dom_ext.rb",
     "lib/grope/env.rb",
     "lib/grope/frame_load_delegate.rb",
     "lib/grope/wso_wrapper.rb",
     "spec/env_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/wso_wrapper.rb"
  ]
  s.homepage = %q{http://github.com/youpy/grope}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A non-GUI library to represent browser environment}
  s.test_files = [
    "spec/env_spec.rb",
     "spec/spec_helper.rb",
     "spec/wso_wrapper.rb",
     "examples/js_minifier.rb",
     "examples/md5.rb",
     "examples/patterns.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

