# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{grope}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["youpy"]
  s.date = %q{2011-02-20}
  s.default_executable = %q{grope}
  s.description = %q{A non-GUI library to represent browser environment using WebKit Framework}
  s.email = %q{youpy@buycheapviagraonlinenow.com}
  s.executables = ["grope"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/grope",
    "examples/js_minifier.rb",
    "examples/js_minifier_sinatra.rb",
    "examples/map_generator.rb",
    "examples/md5.rb",
    "examples/patterns.rb",
    "examples/url2png.rb",
    "grope.gemspec",
    "lib/grope.rb",
    "lib/grope/dom_ext.rb",
    "lib/grope/env.rb",
    "lib/grope/frame_load_delegate.rb",
    "lib/grope/web_resource_load_delegate.rb",
    "lib/grope/wso_wrapper.rb",
    "spec/env_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/wso_wrapper_spec.rb"
  ]
  s.homepage = %q{http://github.com/youpy/grope}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{A non-GUI library to represent browser environment}
  s.test_files = [
    "examples/js_minifier.rb",
    "examples/js_minifier_sinatra.rb",
    "examples/map_generator.rb",
    "examples/md5.rb",
    "examples/patterns.rb",
    "examples/url2png.rb",
    "spec/env_spec.rb",
    "spec/spec_helper.rb",
    "spec/wso_wrapper_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<mechanize>, [">= 1.0.0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<mechanize>, [">= 1.0.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<mechanize>, [">= 1.0.0"])
  end
end

